"""Pose-level functionality for raw frame ingestion and tensor building."""

from text_to_sign_production.legacy_data.pose.analysis import (
    build_pose_build_diagnostic_aggregate_record,
    build_pose_channel_nonzero_distribution_records,
    build_pose_issue_frequency_records,
    build_pose_people_per_frame_distribution_record,
    build_pose_person_selection_fallback_count_records,
)
from text_to_sign_production.legacy_data.pose.anatomy import (
    CROSS_CHANNEL_BODY_SCALE_SEGMENTS,
    CROSS_CHANNEL_HAND_SCALE_SEGMENTS,
    FACE_EYEBROW_REGION_INDICES,
    FACE_HEAD_ANCHOR_INDICES,
    FACE_LOWER_REGION_INDICES,
    FACE_MOUTH_REGION_INDICES,
    FACE_UPPER_REGION_INDICES,
    HAND_BONE_SEGMENTS,
    HAND_DISTAL_CHAIN_INDICES,
    HAND_DISTAL_JOINT_INDICES,
    HAND_FINGER_CHAINS,
    HAND_FINGERTIP_INDICES,
    HAND_PALM_ANCHOR_INDICES,
    UPPER_BODY_BONE_SEGMENTS,
)
from text_to_sign_production.legacy_data.pose.files import discover_frame_files
from text_to_sign_production.legacy_data.pose.parser import parse_frame
from text_to_sign_production.legacy_data.pose.people import (
    DEFAULT_PERSON_SELECTION_POLICY,
    build_person_metadata,
    person_selection_policy_name,
    resolve_person_selection,
    resolve_person_tracking,
    resolve_target_person_index,
)
from text_to_sign_production.legacy_data.pose.tensors import (
    PoseProgressEvent,
    PoseProgressSink,
    build_pose_tensors,
)
from text_to_sign_production.legacy_data.pose.types import (
    FrameFileListing,
    ParsedFrameResult,
    PersonSelectionCandidateScore,
    PersonSelectionPolicy,
    PersonSelectionResult,
    PersonTrackingResult,
    PoseBuildDiagnosticAggregateRecord,
    PoseBuildDiagnostics,
    PoseBuildInput,
    PoseBuildOutput,
    PoseChannelNonzeroDistributionRecord,
    PoseIssueFrequencyRecord,
    PosePeoplePerFrameDistributionRecord,
    PosePersonSelectionFallbackCountRecord,
    PoseValidationIssue,
)
from text_to_sign_production.legacy_data.pose.validate import validate_pose_build

__all__ = [
    "CROSS_CHANNEL_BODY_SCALE_SEGMENTS",
    "CROSS_CHANNEL_HAND_SCALE_SEGMENTS",
    "DEFAULT_PERSON_SELECTION_POLICY",
    "FACE_EYEBROW_REGION_INDICES",
    "FACE_HEAD_ANCHOR_INDICES",
    "FACE_LOWER_REGION_INDICES",
    "FACE_MOUTH_REGION_INDICES",
    "FACE_UPPER_REGION_INDICES",
    "FrameFileListing",
    "HAND_BONE_SEGMENTS",
    "HAND_DISTAL_CHAIN_INDICES",
    "HAND_DISTAL_JOINT_INDICES",
    "HAND_FINGER_CHAINS",
    "HAND_FINGERTIP_INDICES",
    "HAND_PALM_ANCHOR_INDICES",
    "ParsedFrameResult",
    "PersonSelectionCandidateScore",
    "PersonSelectionPolicy",
    "PersonSelectionResult",
    "PersonTrackingResult",
    "PoseBuildDiagnostics",
    "PoseBuildDiagnosticAggregateRecord",
    "PoseBuildInput",
    "PoseBuildOutput",
    "PoseChannelNonzeroDistributionRecord",
    "PoseIssueFrequencyRecord",
    "PosePeoplePerFrameDistributionRecord",
    "PosePersonSelectionFallbackCountRecord",
    "PoseProgressEvent",
    "PoseProgressSink",
    "PoseValidationIssue",
    "UPPER_BODY_BONE_SEGMENTS",
    "build_pose_build_diagnostic_aggregate_record",
    "build_pose_channel_nonzero_distribution_records",
    "build_pose_issue_frequency_records",
    "build_pose_people_per_frame_distribution_record",
    "build_pose_person_selection_fallback_count_records",
    "build_person_metadata",
    "build_pose_tensors",
    "discover_frame_files",
    "person_selection_policy_name",
    "parse_frame",
    "resolve_person_selection",
    "resolve_person_tracking",
    "resolve_target_person_index",
    "validate_pose_build",
]
