DEBUG_WORKFLOW_NAME = "debug"

DEBUG_STAGE_RUNTIME_RESTORE = "debug.runtime.restore"
DEBUG_STAGE_TARGET_RESOLVE = "debug.target.resolve"
DEBUG_STAGE_EVIDENCE_COLLECTION = "debug.evidence.collection"
DEBUG_STAGE_GATE_RECOMPUTE = "debug.gate.recompute"
DEBUG_STAGE_LEAKAGE_INPUTS = "debug.leakage.inputs"
DEBUG_STAGE_LEAKAGE_RELATIONS = "debug.leakage.relations"
DEBUG_STAGE_LEAKAGE_SUMMARIES = "debug.leakage.summaries"
DEBUG_STAGE_TIER_QUALITY = "debug.tier.quality"
DEBUG_STAGE_TIER_DECISION = "debug.tier.decision"
DEBUG_STAGE_VISUALIZATION_RENDER = "debug.visualization.render"
DEBUG_STAGE_REPORT_WRITE = "debug.reports.write"
DEBUG_STAGE_OUTPUT_PUBLISH = "debug.outputs.publish"
