GATE_WORKFLOW_NAME = "gate"

GATE_PASSED_PARTITION = "passed"
GATE_DROPPED_PARTITION = "dropped"

GATE_WORKFLOW_DIRNAME = "gate"
GATE_OUTPUTS_DIRNAME = "outputs"
GATE_PUBLISH_DIRNAME = "publish"
GATE_RUNTIME_DIRNAME = "runtime"

GATE_STAGE_RUNTIME_PLAN = "gate.runtime.plan"
GATE_STAGE_RUNTIME_RESTORE = "gate.runtime.restore"
GATE_STAGE_RUNTIME_VERIFY = "gate.runtime.verify"
GATE_STAGE_INPUT_VALIDATE = "gate.validate.inputs"
GATE_STAGE_SOURCE_BUILD = "gate.processing.source_build"
GATE_STAGE_POSE_BUILD = "gate.processing.pose_build"
GATE_STAGE_DECISION_COMPUTE = "gate.processing.decisions"
GATE_STAGE_PAYLOAD_WRITE = "gate.outputs.payloads"
GATE_STAGE_MANIFEST_WRITE = "gate.outputs.manifests"
GATE_STAGE_REPORT_PROCESSING_SUMMARY_WRITE = "gate.outputs.reports.processing_summary"
GATE_STAGE_REPORT_PROCESSING_DETAIL_WRITE = "gate.outputs.reports.processing_detail"
GATE_STAGE_REPORT_GATE_SUMMARY_WRITE = "gate.outputs.reports.gate_summary"
GATE_STAGE_REPORT_GATE_DETAIL_WRITE = "gate.outputs.reports.gate_detail"
GATE_STAGE_REPORT_SOURCE_ISSUE_SUMMARY_WRITE = "gate.outputs.reports.source_issue_summary"
GATE_STAGE_REPORT_SOURCE_ISSUE_DETAIL_WRITE = "gate.outputs.reports.source_issue_detail"
GATE_STAGE_PUBLISH_PLAN = "gate.publish.plan"
GATE_STAGE_PUBLISH_EXECUTE = "gate.publish.execute"
GATE_STAGE_PUBLISH_VERIFY = "gate.publish.verify"
